version: "3.7"
services:
  postgres:
    image: postgres:16.1
    volumes:
      - ./backend/docker:/docker-entrypoint-initdb.d
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${POSTGRES_PORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-q"]

  fms_frontend:
    depends_on:
      openapi_generator:
        condition: service_completed_successfully
      fms_backend:
        condition: service_started
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  fms_backend:
    depends_on:
      secret_generator:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    build:
      context: ./backend
      dockerfile: ./Fms/Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./backend/Fms/openapi:/src/Fms/openapi
      - ./backend/Fms/secrets.json:/app/secrets.json:ro
    environment:
      POSTGRES_HOST: postgres
    env_file:
      - .env

  openapi_generator:
    build:
      context: ./utils/openapi_generator
    volumes:
      - ./backend/Fms/openapi:/openapi:ro
      - ./frontend/generated:/frontend/generated

  secret_generator:
    build:
      context: ./utils/secret_generator
    volumes:
      - ./backend/Fms:/out
